# Simulating Coin Flips

In [1]:
import numpy as np

### Generate random integers

In [2]:
# np.random.randint?

In [3]:
# outcome of one coin flip
np.random.randint(2)

0

In [4]:
# outcome of ten thousand coin flips
np.random.randint(2, size=10000)

array([0, 0, 1, ..., 0, 0, 1])

In [5]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5007

### Generates a random sample (loaded)

In [6]:
# np.random.choice?

In [7]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [8]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([1, 0, 0, ..., 1, 0, 0])

In [9]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.4985

In [10]:
# outcomes of ten thousand biased (loaded) coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2])

array([1, 0, 0, ..., 0, 0, 0])

In [11]:
# mean outcome of ten thousand biased (loaded) coin flips
np.random.choice([0, 1], size=10000, p=[0.8, 0.2]).mean()

0.202

In [12]:
# outcome of 50 dice rolls
np.random.choice([1,2,3,4,5,6], size=50)

array([6, 4, 5, 2, 2, 3, 6, 3, 2, 4, 5, 4, 6, 4, 5, 1, 2, 1, 2, 6, 4, 2,
       5, 3, 3, 4, 1, 3, 1, 3, 4, 3, 5, 3, 3, 5, 1, 4, 5, 5, 6, 3, 3, 2,
       4, 6, 5, 5, 3, 1])

In [13]:
# mean outcome of 50 dice rolls
np.random.choice([1,2,3,4,5,6], size=1000).mean()

3.532

In [14]:
# calculating mean of biased (loaded) die thrown 50 times 
np.random.choice([1,2,3,4,5,6], size=50, p=[0,0.5,0,0.5,0,0]).mean()

2.76